import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const roboto = {
  font: "Roboto",
  url: "https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap",
};
const lato = {
  font: "Lato",
  url: "https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap",
};
const oswald = {
  font: "Oswald",
  url: "https://fonts.googleapis.com/css2?family=Oswald:wght@400;700&display=swap",
};
const montserrat = {
  font: "Montserrat",
  url: "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap",
};
const raleway = {
  font: "Raleway",
  url: "https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap",
};
const openSans = {
  font: "Open Sans",
  url: "https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap",
};
const poppins = {
  font: "Poppins",
  url: "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap",
};
const merriweather = {
  font: "Merriweather",
  url: "https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap",
};

const fonts = [
  roboto,
  lato,
  oswald,
  montserrat,
  raleway,
  openSans,
  poppins,
  merriweather,
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {fonts.map((font, index) => (
          <link key={index} href={font.url} rel="stylesheet" />
        ))}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
